version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: netbank
      POSTGRES_USER: netbank
      POSTGRES_PASSWORD: netbank
    ports:
    - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080