version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - adminer
    restart: always
    ports:
      - 8001:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/netbank

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: percona:ps-8
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: netbank
      MYSQL_PASSWORD: netbank
      MYSQL_DATABASE: netbank
      MYSQL_ROOT_PASSWORD: password
